frictionlessdata/tableschema-js

- index.js
- package.json
- test/types.js
- types.js
- utilities.js
Some date string parse by python library may not be parsed by js ```Date()```.
> Ported types.py, with tests

- package.json
Added ```moment.js``` into dependencies list.
> Added missed dependencies

- models.js
- package.json
- utilities.js
> Replaced promise-polyfill to bluebird (#9)

- test/types.js
- types.js
Also some fixes related to type handling in the library.
Main thing to notice is that `0 instanceof Number === false`
> Add support for groupChar and decimalChar

- src/types.js
- test/types.js
@roll, @pwalsh, @Hypercubed
Accordingly to the discussion in the issue (it fixes #33) I just made those changes.
> Date casting return native Date JS object instead of moment

- README.md
- package.json
> Add schemas folder to the build

- .gitignore
- package.json
- src/types.js
- test/types.js
> Fixed string type

- README.md
- src/table.js
- test/table.js
- connects https://github.com/frictionlessdata/datapackage-js/issues/90
> Improved foreign keys API

- README.md
- src/field.js
- src/schema.js
- src/table.js
- test/field.js
- test/schema.js
- test/table.js
> Improved error messages

- .eslintrc
- data/data_infer_formats.csv
- src/config.js
- src/schema.js
- test/infer.js
> Added support for formats inferring

- src/schema.js
- src/types/string.js
- test/infer.js
> Added heuristics to the infer function

- README.md
- src/schema.js
- src/table.js
- test/table.js
> Updated `forceCast` implementation

- package.json
> Upgrade moment to 2.21.0

- package.json
- src/table.js
- test/table.js
Please check the commit messages
> Autodetect CSV delimiter

- README.md
- index.d.ts
- package.json
Pull request consists of the following non-functional changes:
- Adds type definitions for users of TypeScript, to aid in typing checking and intellisense.
- Minor documentation changes as a result of constructing the TypeScript definitions.
> TypeScript Definitions and Documentation

- Makefile
- README.md
- package.json
- src/errors.js
- src/field.js
- src/index.js
- src/infer.js
- src/schema.js
- src/table.js
- src/validate.js
> Generate API Reference from docstrings

- package.json
- src/table.js
> Rebased on csv-parse@4

- src/field.js
- src/schema.js
- test/field.js
- test/schema.js
- test/table.js
> Improve error messages on bad constraints

- src/types/date.js
- src/types/datetime.js
- src/types/time.js
> Suppress the moment library's warning on the "any" data/time format

- src/types/time.js
- test/schema.js
- test/types/time.js
> Fixed any format for time

- src/table.js
- test/table.js
> Added csv sniffer fallback

- data/issue_175.csv
- src/table.js
- test/infer.js
> Fixed delimiter inferring

- package.json
- src/profiles/table-schema.json
> Updated to axios@0.21.1

- package.json
Update momentjs dependency, per https://github.com/advisories/GHSA-wc69-rhjr-hc9g
#137 previous fix of similar issue.
Please preserve this line to notify @aivuk (lead of this repository)
> Fix https://github.com/advisories/GHSA-wc69-rhjr-hc9g
